apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: roshka-backend
  annotations:
    github.com/project-slug: cone011/roshka-backend
spec:
  type: other
  lifecycle: unknown
  owner: guests
